name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Build docs
      run: |
        mkdocs -v build
        : > site/.nojekyll
        echo -n '101.ustclug.org' > site/CNAME
    - name: Deploy to GitHub Pages
      run: |
        CINFO="$(git log -1 --pretty="%an: [%h] %s")"
        git clone --depth=1 --branch=gh-pages --single-branch --no-checkout \
          "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" test
        mv test/.git site/.git && rmdir test/
        pushd site/ &>/dev/null
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "Auto deploy from GitHub Actions build ${GITHUB_RUN_NUMBER}" \
          -m "$CINFO"
        git push
        popd &>/dev/null
